### PR TITLE
Cleaned up PCB routes and positions; Converted I2C to Adafruit std pinout.

### PR DESCRIPTION
**Pull request by ayourk**
Have Git ignore Kicad generated files.
I recommend reviewing a copy from my fork.

### CODE REVIEW

**Comment by KRSynthWorx** [comment]
Hello ayourk,
Thank you for your interest and nice work on the PCB layout and additions to the project. When I originally put this
together I did not have a need for 3.3 volt support and additional connectors besides the reversed SCL/SDA pins that
I have on the I2C 3 & 4 header connectors.

In order to provide 3.3 volt support, more is needed besides providing a 5v to 3.3v regulator. The TTL latch (output port)
and TTL buffer (input port) on the Z80-Retro! parallel printer port are 5v ONLY logic and they reference the Z80-Retro!
main 5v supply. The I2C/SPI Master Interface Board uses these 5v TTL signals and buffers them for compatibility with the
I2C and SPI master mode protocols.

The I2C interface standards specify open drain buffers with pull-up resistors on the SCL/SDA lines to the same power rail.
The slave device also has pull-up resistors on these lines to the power rail putting them in parallel with the ones on the
I2C/SPI Master Interface Board. This allows multiple connected slave devices to lower the SCL/SDA lines by sinking current
through the slave device driver circuit. If the slave device requires a 3.3v supply, then the master SCL/SDA open drain
buffers and pull-up resistors on the I2C/SPI Master Interface Board also must be referencing the same 3.3v supply. This
presents a problem as these buffers are connected to the Z80-Retro! TTL 5v ports described above.

The SPI buffer on the I2C/SPI Master Interface Board has a similar problem with the MISO/MOSI/SCLK/CS lines as they are
all 5v TTL signals referencing the Z80-Retro! 5v supply. Although it sources current instead of sinking it. Note that you
can get away with intermixing the 5/3.3 volt signals to an SPI slave that has it's own 3.3v regulator provided you form
a resistor voltage divider on the MOSI/SCLK/CS lines and that the slave does not transmit anything back to the master on
the MISO line and that it is left disconnected. See the comments in the oled_test.asm test program in this repo.

In order to accommodate either 5v or 3.3v slave devices, the Z80-Retro! parallel printer port TTL lines need to be isolated
and level shifted from/to 5v and 3.3v and the I2C/SPI buffers need to be powered by the 3.3v supply. The pull-up resistors
on the I2C open drain buffers also need to reference the 3.3v supply. You also cannot mix both 5v and 3.3v slave devices on
the same buss. Some method of switching between 5v and 3.3v mode is needed as well as the described level shifting. The
level shifting can often be accomplished with a MOSFET between each of the Z80-Retro! parallel printer port lines and the
I2C SCL/SDA and SPI MISO/MOSI/SCLK/CS lines. There are also commercially available level shifter buffers designed for this
purpose. The 5/3.3v switching can be accomplished with a jumper. 

I currently do not have the spare time to be able to work on these details. Please feel free to experiment on your own
though and publish your versions directly on your fork of this project.

Thank you again for your interest in this project.
~Kenny

**Comment by johnwinans** [comment]
You should be able to use the same circuit I used to shift the PI 3.3V to 5V on the Retro programmer board.

**Comment by ayourk** [comment]
> You should be able to use the same circuit I used to shift the PI 3.3V to 5V on the Retro programmer board.

I copied at least some of this from there.  That's why I have the same voltage regulator you use in this design.

**Comment by ayourk** [comment]
I've updated my repo to address your concerns.

**Pull request closed without merging**
